// Generated by CoffeeScript 1.4.0
var ease_bezier, ease_func, fact;

fact = function(n) {
  if (n > 0) {
    return n * fact(n - 1);
  }
  return 1;
};

ease_func = function(ps, t, start, end) {
  var mult, offset, value;
  mult = end - start;
  offset = start;
  value = ease_bezier(ps, t);
  value *= mult;
  return value += offset;
};

ease_bezier = function(ps, t) {
  var eq, i, value, _i, _ref;
  value = 0;
  eq = '';
  for (i = _i = 0, _ref = ps.length; _i < _ref; i = _i += 1) {
    value += fact(ps.length - 1) / (fact(ps.length - 1 - i) * fact(i)) * Math.pow(1 - t, ps.length - 1 - i) * Math.pow(t, i) * ps[i];
    eq = eq + (ps.length - 1) + '!/(' + (ps.length - 1 - i) + '!*' + i + '!)*' + '(1 - t)^' + (ps.length - 1 - i) + '*t^' + i + '*' + ps[i] + ' + ';
  }
  return value;
};
