// Generated by CoffeeScript 1.4.0

$.fn.scale = function() {
  var transform;
  transform = $(this).css('transform') || 0;
  console.log(transform);
  transform = transform.substring(transform.indexOf('scale(') + 6, transform.indexOf(')', transform.indexOf('scale(')));
  transform = transform.substring(0, transform.indexOf(','));
  return transform;
};
