// Generated by CoffeeScript 1.4.0
var Word;

Word = (function() {

  function Word(values) {
    var _ref, _ref1, _ref2, _ref3, _ref4;
    values = values != null ? values : {};
    this.selector = (_ref = values.selector) != null ? _ref : '';
    this.x = (_ref1 = values.x) != null ? _ref1 : 0;
    this.y = (_ref2 = values.y) != null ? _ref2 : 0;
    this.xOrigin = (_ref3 = values.xOrigin) != null ? _ref3 : 0;
    this.yOrigin = (_ref4 = values.yOrigin) != null ? _ref4 : 0;
  }

  Word.prototype.center = function() {
    var cumWidth, cumWidthLast, elem, widths;
    cumWidth = 0;
    cumWidthLast = 0;
    widths = (function() {
      var _i, _len, _ref, _results;
      _ref = $(this.selector);
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        elem = _ref[_i];
        cumWidthLast = cumWidth;
        cumWidth += $(elem).width();
        _results.push(cumWidthLast);
      }
      return _results;
    }).call(this);
    widths = (function() {
      var _i, _len, _results;
      _results = [];
      for (_i = 0, _len = widths.length; _i < _len; _i++) {
        elem = widths[_i];
        _results.push(elem - cumWidth / 2);
      }
      return _results;
    })();
    return widths;
  };

  return Word;

})();
